#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (new \Rapid\Laplus\Tests\TestCase('test'))->createApplication()
    ->handleCommand(new ArgvInput);

exit($status);
